@baseurl = http://localhost:8080/api/v1

### get user videos
# @name getUserVideos
GET {{baseurl}}/videos/
Content-Type: application/json
Authorization: Bearer {{authToken}}

> {%
    if (response.body.data && response.body.data.length > 0) {
        client.global.set("videoId", response.body.data[0].id);
    } else {
        client.log("No videos found for this user");
    }
%}

### get video by id
# @name getdVideoById
GET {{baseurl}}/videos/{{videoId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get video info
# @name getVideoInfo
POST {{baseurl}}/videos/info
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "url": "https://www.youtube.com/watch?v=8PC5JnGHQNU"
}

### Download audio
# @name downloadAudio
POST {{baseurl}}/videos/audio
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "url": "https://www.youtube.com/watch?v=8PC5JnGHQNU"
}

### transcribe video
# @name transcribe
POST {{baseurl}}/videos/transcribe
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "url": "https://www.youtube.com/watch?v=Dba9Kyy73Uk"
}

> {%
    client.global.set("jobId", response.body.data.jobId);
%}

### get transcription status
# @name getTranscriptionStatus
GET {{baseurl}}/videos/transcribe/{{jobId}}/status
Content-Type: application/json
Authorization: Bearer {{authToken}}

### get all running jobs
# @name getAllRunningJobs
POST {{baseurl}}/videos/jobs/running
Content-Type: application/json
Authorization: Bearer {{authToken}}